# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/harmon/Documents/grepos/xilinx_learning/seq_latch_comb/seq_latch_comb.cache/wt [current_project]
set_property parent.project_path /home/harmon/Documents/grepos/xilinx_learning/seq_latch_comb/seq_latch_comb.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/harmon/Documents/grepos/xilinx_learning/seq_latch_comb/seq_latch_comb.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/harmon/Documents/grepos/xilinx_learning/seq_latch_comb/seq_latch_comb.srcs/sources_1/new/seq_latch_comb.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top seq_latch_comb -part xc7k70tfbv676-1


write_checkpoint -force -noxdef seq_latch_comb.dcp

catch { report_utilization -file seq_latch_comb_utilization_synth.rpt -pb seq_latch_comb_utilization_synth.pb }
